[project]
name = "asynctnt"
description = "A fast Tarantool Database connector for Python/asyncio."
authors = [
    { name = "igorcoding", email = "igorcoding@gmail.com" }
]
license-files = ["LICENSE.txt"]
dynamic = ["version"]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Framework :: AsyncIO",
    "Operating System :: POSIX",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    'Programming Language :: Python :: Implementation :: CPython',
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Database :: Front-Ends"
]
requires-python = '>=3.9.0'
readme = "README.md"
dependencies = [
    "ruff>=0.14.13",
]

[project.urls]
github = "https://github.com/igorcoding/asynctnt"

[project.optional-dependencies]
test = [
    'ruff',
    'uvloop>=0.12.3; platform_system != "Windows" and platform.python_implementation != "PyPy"',
    'pytest>=8.0.0',
    'pytest-asyncio>=0.24.0',
    'pytest-cov',
    'coverage[toml]',
    'pytz',
    "Cython==3.2.4",  # for coverage
]

docs = [
    'Sphinx>=5',
    'sphinx_rtd_theme',
    'sphinxcontrib-asyncio',
    'myst-parser',
    'sphinx-autodoc-typehints',
    'sphinx-autoapi',
]

[build-system]
requires = [
    "setuptools>=77",
    "wheel",
    "Cython==3.2.4",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
include = ["asynctnt", "asynctnt.*"]

[tool.setuptools.exclude-package-data]
"*" = ["*.c", "*.h"]

[tool.pytest.ini_options]
addopts = "--strict-markers --tb native"
testpaths = "tests"
filterwarnings = "default"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
    "min_version(version): skip if Tarantool version < specified",
    "max_version(version): skip if Tarantool version >= specified",
    "min_bin_version(version): skip based on binary version",
]

[tool.coverage.run]
branch = true
plugins = ["Cython.Coverage"]
parallel = true
source = ["asynctnt/", "tests/"]
omit = [
    "*.pxd",
    "asynctnt/_testbase.py",
    "asynctnt/instance.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self\\.debug",
    "if debug",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.",
]
show_missing = true

[tool.coverage.html]
directory = "htmlcov"

[tool.ruff]
extend-exclude = [".venv*", "env*", "venv*"]

[tool.ruff.format]
# Аналогично black, двойные кавычки
quote-style = "double"

# Аналогично black, пробелы вместо табов
indent-style = "space"

# Аналогично black, уважаем trailing commas
skip-magic-trailing-comma = false

# Аналогично black, автоматически определяем подходящее окончание строки.
line-ending = "auto"

[tool.ruff.lint]
# Список кодов или префиксов правил, которые следует считать исправляемыми. (https://docs.astral.sh/ruff/settings/#fixable)
# По умолчанию все правила считаются исправляемыми.
fixable = ["I", "RUF022", "RUF023", "F401"]
preview = true

select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
    "T20", # flake8-print
]
ignore = [
    "E501", # line too long, handled by black
    "B008", # do not perform function calls in argument defaults
    "C901", # too complex
]

[tool.ruff.lint.isort]
# Позволяет использовать as в комбинации с группировкой  (https://docs.astral.sh/ruff/settings/#isort-combine-as-imports)
#from package import (
#    func1 as foo,
#    func2 as boo,
#)
combine-as-imports = true

# Воспринимать следующие пакеты в качестве stdlib       (https://docs.astral.sh/ruff/settings/#isort-extra-standard-library)
extra-standard-library = ["typing_extensions"]

section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder"
]

# Не добавлять пустую строку перед данными секциям      (https://docs.astral.sh/ruff/settings/#isort-no-lines-before)
no-lines-before = []

[tool.ruff.lint.pep8-naming]
# если навесить данные декораторы, то можно использовать cls    (https://docs.astral.sh/ruff/settings/#pep8-naming-classmethod-decorators)
# в качестве первого аргумента.
classmethod-decorators = ["cached_classproperty", "classproperty"]
